### ISSUE TITLE
Could not pass event PlayerTeleportEvent to NetherView v1.0.0

### ISSUE THREAD

**Issue by Fargus5** [GorgeousOne/NetherView#10]
> 

[02:04:27] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to NetherView v1.0.0
--
1677 | java.lang.NullPointerException: null
1678 | at org.bukkit.craftbukkit.v1_15_R1.block.data.CraftBlockData.toNMS(CraftBlockData.java:201) ~[patched_1.15.2.jar:git-Paper-226]
1679 | at org.bukkit.craftbukkit.v1_15_R1.block.data.CraftBlockData.set(CraftBlockData.java:96) ~[patched_1.15.2.jar:git-Paper-226]
1680 | at org.bukkit.craftbukkit.v1_15_R1.block.impl.CraftEndRod.setFacing(CraftEndRod.java:27) ~[patched_1.15.2.jar:git-Paper-226]
1681 | at me.gorgeousone.netherview.blockcache.Transform.rotateData(Transform.java:122) ~[?:?]
1682 | at me.gorgeousone.netherview.blockcache.ProjectionCache.createBlockCopies(ProjectionCache.java:139) ~[?:?]
1683 | at me.gorgeousone.netherview.blockcache.ProjectionCache.<init>(ProjectionCache.java:30) ~[?:?]
1684 | at me.gorgeousone.netherview.handlers.PortalHandler.linkPortalTo(PortalHandler.java:152) ~[?:?]
1685 | at me.gorgeousone.netherview.listeners.TeleportListener.onPortalTravel(TeleportListener.java:66) ~[?:?]
1686 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1254.execute(Unknown Source) ~[?:?]
1687 | at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-226]
1688 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-226]
1689 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-226]
1690 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-226]
1691 | at net.minecraft.server.v1_15_R1.EntityPlayer.a(EntityPlayer.java:950) ~[patched_1.15.2.jar:git-Paper-226]
1692 | at net.minecraft.server.v1_15_R1.Entity.doPortalTick(Entity.java:2254) ~[patched_1.15.2.jar:git-Paper-226]
1693 | at net.minecraft.server.v1_15_R1.Entity.entityBaseTick(Entity.java:444) ~[patched_1.15.2.jar:git-Paper-226]
1694 | at net.minecraft.server.v1_15_R1.EntityLiving.entityBaseTick(EntityLiving.java:244) ~[patched_1.15.2.jar:git-Paper-226]
1695 | at net.minecraft.server.v1_15_R1.Entity.tick(Entity.java:419) ~[patched_1.15.2.jar:git-Paper-226]
1696 | at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2347) ~[patched_1.15.2.jar:git-Paper-226]
1697 | at net.minecraft.server.v1_15_R1.EntityHuman.tick(EntityHuman.java:165) ~[patched_1.15.2.jar:git-Paper-226]
1698 | at net.minecraft.server.v1_15_R1.EntityPlayer.playerTick(EntityPlayer.java:442) ~[patched_1.15.2.jar:git-Paper-226]
1699 | at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:150) ~[patched_1.15.2.jar:git-Paper-226]
1700 | at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.15.2.jar:git-Paper-226]
1701 | at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-226]
1702 | at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1328) ~[patched_1.15.2.jar:git-Paper-226]
1703 | at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-226]
1704 | at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-226]
1705 | at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]
1706 | at java.lang.Thread.run(Thread.java:834) [?:?]
1707 | [02:04:52] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to NetherView v1.0.0
1708 | java.lang.NullPointerException: null
1709 | at org.bukkit.craftbukkit.v1_15_R1.block.data.CraftBlockData.toNMS(CraftBlockData.java:201) ~[patched_1.15.2.jar:git-Paper-226]
1710 | at org.bukkit.craftbukkit.v1_15_R1.block.data.CraftBlockData.set(CraftBlockData.java:96) ~[patched_1.15.2.jar:git-Paper-226]
1711 | at org.bukkit.craftbukkit.v1_15_R1.block.impl.CraftEndRod.setFacing(CraftEndRod.java:27) ~[patched_1.15.2.jar:git-Paper-226]
1712 | at me.gorgeousone.netherview.blockcache.Transform.rotateData(Transform.java:122) ~[?:?]
1713 | at me.gorgeousone.netherview.blockcache.ProjectionCache.createBlockCopies(ProjectionCache.java:139) ~[?:?]
1714 | at me.gorgeousone.netherview.blockcache.ProjectionCache.<init>(ProjectionCache.java:30) ~[?:?]
1715 | at me.gorgeousone.netherview.handlers.PortalHandler.linkPortalTo(PortalHandler.java:152) ~[?:?]
1716 | at me.gorgeousone.netherview.listeners.TeleportListener.onPortalTravel(TeleportListener.java:66) ~[?:?]
1717 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1254.execute(Unknown Source) ~[?:?]
1718 | at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-226]
1719 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-226]
1720 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-226]
1721 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-226]
1722 | at net.minecraft.server.v1_15_R1.EntityPlayer.a(EntityPlayer.java:950) ~[patched_1.15.2.jar:git-Paper-226]
1723 | at net.minecraft.server.v1_15_R1.Entity.doPortalTick(Entity.java:2254) ~[patched_1.15.2.jar:git-Paper-226]
1724 | at net.minecraft.server.v1_15_R1.Entity.entityBaseTick(Entity.java:444) ~[patched_1.15.2.jar:git-Paper-226]
1725 | at net.minecraft.server.v1_15_R1.EntityLiving.entityBaseTick(EntityLiving.java:244) ~[patched_1.15.2.jar:git-Paper-226]
1726 | at net.minecraft.server.v1_15_R1.Entity.tick(Entity.java:419) ~[patched_1.15.2.jar:git-Paper-226]
1727 | at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2347) ~[patched_1.15.2.jar:git-Paper-226]
1728 | at net.minecraft.server.v1_15_R1.EntityHuman.tick(EntityHuman.java:165) ~[patched_1.15.2.jar:git-Paper-226]
1729 | at net.minecraft.server.v1_15_R1.EntityPlayer.playerTick(EntityPlayer.java:442) ~[patched_1.15.2.jar:git-Paper-226]
1730 | at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:150) ~[patched_1.15.2.jar:git-Paper-226]
1731 | at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.15.2.jar:git-Paper-226]
1732 | at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-226]
1733 | at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1328) ~[patched_1.15.2.jar:git-Paper-226]
1734 | at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-226]
1735 | at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-226]
1736 | at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]
1737 | at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Fargus5** [comment]
Solved by restarting the server
