### ISSUE TITLE
1.16.2 doesnt work

### ISSUE THREAD

**Issue by Dycool** [GorgeousOne/NetherView#38]
**Describe the bug**
plugin does not work in 1.16.2

**To Reproduce**
1. create a 1.16.2 spigot server
2. Create portal
3. go to nether and it doesnt work
or
1. do /toggleportalview and boom error

**Expected behavior**
It should appear errors on the logs

**Console logs**
 org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1005) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at net.minecraft.server.v1_16_R2.PacketPlayInFlying.a(SourceFile:122) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at net.minecraft.server.v1_16_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.server.v1_16_R2.ChunkCoordIntPair exists in class PacketPlayOutMultiBlockChange.
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:363) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:343) ~[?:?]
        at me.gorgeousone.netherview.handlers.PacketHandler.displayFakeBlocks(PacketHandler.java:71) ~[?:?]
        at me.gorgeousone.netherview.handlers.PacketHandler.removeFakeBlocks(PacketHandler.java:59) ~[?:?]
        at me.gorgeousone.netherview.handlers.ViewHandler.hidePortalProjection(ViewHandler.java:131) ~[?:?]
        at me.gorgeousone.netherview.handlers.ViewHandler.displayClosestPortalTo(ViewHandler.java:174) ~[?:?]
        at me.gorgeousone.netherview.listeners.PlayerMoveListener.onPlayerMove(PlayerMoveListener.java:57) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot.jar:git-Spigot-379750e-fe4efd1]
        ... 18 more

**Screenshots**
![image](https://user-images.githubusercontent.com/65285981/90989743-0a5cdd00-e594-11ea-92c6-254a8f681738.png)

**Server version and plugin version
1.16.2 - 1.5.0

**Comment by GorgeousOne** [comment]
Now it does
