### ISSUE TITLE
Different locale crashes plugin

### ISSUE THREAD

**Issue by NotAShelf** [GorgeousOne/NetherView#56]
Paper Version: paper-220
Server Version: 1.16.3
NetherView Version: 2.1.0
Protocollib Version: Latest dev build (version 4.6.0-SNAPSHOT-b480)

`[21:59:08 ERROR]: Error occurred while enabling NetherView v2.1.0 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.WHİTE_TERRACOTTA
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.Material.valueOf(Material.java:89) ~[patched_1.16.3.jar:git-Paper-220]
        at me.gorgeousone.netherview.wrapper.blocktype.AquaticBlockType.<init>(AquaticBlockType.java:49) ~[?:?]
        at me.gorgeousone.netherview.wrapper.blocktype.BlockType.of(BlockType.java:35) ~[?:?]
        at me.gorgeousone.netherview.NetherViewPlugin.deserializeWorldBorderBlockType(NetherViewPlugin.java:390) ~[?:?]
        at me.gorgeousone.netherview.NetherViewPlugin.loadWorldBorderBlockTypes(NetherViewPlugin.java:374) ~[?:?]
        at me.gorgeousone.netherview.NetherViewPlugin.loadConfigData(NetherViewPlugin.java:318) ~[?:?]
        at me.gorgeousone.netherview.NetherViewPlugin.onEnable(NetherViewPlugin.java:108) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-220]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-220]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-220]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[21:59:08 INFO]: [NetherView] Disabling NetherView v2.1.0
[21:59:08 ERROR]: Error occurred while disabling NetherView v2.1.0 (Is it up to date?)
java.lang.NullPointerException: null
        at me.gorgeousone.netherview.NetherViewPlugin.backupPortals(NetherViewPlugin.java:424) ~[?:?]
        at me.gorgeousone.netherview.NetherViewPlugin.onDisable(NetherViewPlugin.java:177) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.3.jar:git-Paper-220]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.3.jar:git-Paper-220]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.3.jar:git-Paper-220]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.3.jar:git-Paper-220]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-220]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-220]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]`

**Comment by GorgeousOne** [comment]
This error can only occur if you edited the source code. It says that the fall back material `WHİTE_TERRACOTTA` could not be resolved (because you used a `İ` with dot instead of a latin `I`). The fall back value is used if the config value is not working so it is _hard coded_ in the plugin. It _cannot_ be changed by users.

So I don't really know what kind of game you are playing here, but I think this is not Nether View 2.1.0 that I compiled.

**Comment by NotAShelf** [comment]
Good sir, this is _exactly_ what you have uploaded on spigot. I have no interest in editing your source code and even if I did, I do not know how. I request you to at least contact be before accusing me of editing your source code (once again, I do **not** know how)

**Comment by GorgeousOne** [comment]
I apologize for jumping to conclusions.
From what I can see from this error it looks like something in the source code was changed because otherwise I would not know how this error can occur.
Did you try to delete the config.yml file and reload the plugin? I think it should work then.

**Comment by NotAShelf** [comment]
From start, I have stopped my server (with /stop as I'm localhosting the paper server) and uploaded NeverView and Protocollib. And when I started the server again (I use a start script, if that makes a difference) the error was on my console.

My local language, Turkish, does not have I (and as you may have guessed, uses the İ with a dot as capital i) and my best guess is that my windows language may have created the issue.

**Comment by GorgeousOne** [comment]
Okay, after some research I tried to fix this. Do you want to try this version here?
[NetherView-v2.1.1-unofficial.zip](https://github.com/GorgeousOne/NetherView/files/5365233/NetherView-v2.1.1-unofficial.zip)
Let me know if it works or not

**Comment by GorgeousOne** [comment]
Okay for me this works now. I tried switching the java locale to Turkey in the batch file to start my server:
`java -Duser.language=tr -Duser.region=TR -jar paper-220.jar`
I could reproduce your error you had earlier but with the attached jar it worked fine.

**Comment by NotAShelf** [comment]
Adding `-Duser.language=en` to my start.bat has resolved the error, thank you very much for your assistance!
